### ISSUE TITLE
Need to change our test name from patch to update

### ISSUE THREAD

**Issue by eladkug** [cyberark/secrets-provider-for-k8s#108]
Our test TEST_ID_6_no_patch_permission_to_secret need to be change to TEST_ID_6_no_update_permission_to_secret.
This is related to our change from [patch to update](https://github.com/cyberark/secrets-provider-for-k8s/pull/79), the implementation is with update.

DOD:
- [x] Automation pass

**Comment by orenbm** [comment]
fixed by #115
