### ISSUE TITLE
Secrets Provider (P2) - Research, Update and Removal of Deployment

### ISSUE THREAD

**Issue by sigalsax** [cyberark/secrets-provider-for-k8s#113]
A valid solution requires that the Secrets provider be decoupled from customer applications (AKA not sitting with each app in same pod). 

As part of this research, we also need to evaluate the lifecycle for the solution, supporting the upgrade and removal of the secrets provider deployment.

Solution doc: https://github.com/cyberark/secrets-provider-for-k8s/pull/122/files

**Comment by cbarga** [comment]
Due to the volume of potential apps running on > 2000 clusters, my company is definitely interested in this.
