### ISSUE TITLE
Secrets Provider - Add SLA performance tests

### ISSUE THREAD

**Issue by abrahamko** [cyberark/secrets-provider-for-k8s#172]
We need to know what is the capacity of the secrets provider.
More specifically, how many secrets providers can 1 follower support.
We need to test it constantly so we can guarantee it in our releases.
See [SLA Performance tests design](https://github.com/cyberark/secrets-provider-for-k8s/blob/master/design/milestone_1_2_design_doc.md#performance-tests) for more info.

Secrets Provider should fail if not finished in 1 minute after launch.

DOD:
- [x] Add SLA performance tests
- [x]  Write the max secrets provider that can be for specific follower (based on your assumption)
- [x]  Write the max secrets a secret provider can handle

**Comment by Tovli** [comment]
Opened https://github.com/cyberark/secrets-provider-for-k8s/issues/229 as a follow up task

**Comment by izgeri** [comment]
@abrahamko was there a document summarizing the work you did here? I can't find a reference to it
