### ISSUE TITLE
Secrets provider - Support OC4.3 

### ISSUE THREAD

**Issue by eladkug** [cyberark/secrets-provider-for-k8s#173]
We want to add support to OC4.3 in addition to what we have today (OC3.11, GKE).
To support another environment we have to be aligned to k8s-conjur-deploy master.
Today we are working with specific branch on k8s-conjur-deploy  repo which make it difficult to add changes under infra. Need to make sure we are working with updated branch on k8s-conjur-deploy and than add some fix there including OC4.3

DOD:

- [x] Working with master branch on k8s-conjur-deploy
- [ ] Improve our infra and make this repo more stable
- [ ] Support OC4.3

**Comment by Tovli** [comment]
We will continue with an advanced version of ocp
closing this
