### ISSUE TITLE
Secrets Provider - Add configurable retry mechanism

### ISSUE THREAD

**Issue by sigalsax** [cyberark/secrets-provider-for-k8s#174]
For this card we need to make our retry mechanism configurable for better troubleshooting and to support network lag.

DOD
- [x] Add `RETRY_COUNT` and `TIMEOUT` Helm chart ({{- if .Values.environment.timeout }})
- [x] Update Json schema accordingly
- [x] Make the retry mechanism configurable using env vars passed from defaults in the custom-values.yaml (default should be defined in code TIMEOUT: 30 seconds, RETRY_COUNT: 3
- [x] Add proper, last log from here https://github.com/cyberark/conjur-docs/issues/1046

**Comment by alexkalish** [comment]
@sigalsax: Could you provide some details about why this change was made?  What motivated it?  Trying to update the release notes and would like to understand it a bit better.  In the future, it would be great if the user value of a change could be captured in the story and the CHANGELOG entry, whenever possible.  Thanks!

**Comment by alexkalish** [comment]
@sigalsax: Two more questions:
1. How are these values configured?  Looking at the PR diff, they appear to be ENV variables that can be set in the Helm chart.  Is that right?
2. Are these configuration values and their proper use documented?

**Comment by sigalsax** [comment]
@alexkalish to start, there was a problem in our release process pushing to dockerhub due to an infra issue so this bump was not successful. The problem has since been fixed and we plan to release a new version when our documentation will be ready (which is in progress) @eladkug and I [created this release doc](https://ca-il-confluence.il.cyber-ark.com/display/rndp/%5B11.7%5D+CyberArk+Secret+Provider+for+K8s+Release) which you might find helpful in the release process. 

> it would be great if the user value of a change could be captured in the story and the CHANGELOG entry, whenever possible

Noted! No problem 💯 I want to note that the retry mechanism wasn't intended to be forward facing/documented and be used for troubleshooting purposes. @InbalZilberman feel free to expand here. 

The idea for this feature came from the [secrets provider epic](https://app.zenhub.com/workspaces/palmtree-5d99d900491c060001c85cba/issues/cyberark/secrets-provider-for-k8s/163) created by @InbalZilberman and decided to stay as an internal feature.

Regarding your questions:

> How are these values configured? Looking at the PR diff, they appear to be ENV variables that can be set in the Helm chart. Is that right?

Indeed! I created a demo which I just tagged you in in slack. Feel free to give feedback 🙏  But in short, yes in the custom-values.yaml the customer would create and provide for us, they would need to add the following

```
environment:
  conjur:
    retryIntervalSec:  1
    retryCountLimit:  5
```
or whatever other configurations they require. They would then pass the custom-values.yaml in during installation and our Helm chart (see a snippet below) would be filled with those values. 

```
{{- if .Values.environment.conjur.retryIntervalSec }}
- name: RETRY_INTERVAL_SEC
   value: {{ .Values.environment.conjur.retryIntervalSec | quote }}
{{- end }}

{{- if kindIs "float64" .Values.environment.conjur.retryCountLimit }}
- name: RETRY_COUNT_LIMIT
   value: {{ .Values.environment.conjur.retryCountLimit | quote }}
{{- end }}
```

> Are these configuration values and their proper use documented?

This ability will not be documented as we wanted this for troubleshooting purposes for our devs and SEs
@InbalZilberman please feel free to expand on the motivation to keep this functionality internal and not documented
