### ISSUE TITLE
Secrets Provider - Account for initial error in authn-client

### ISSUE THREAD

**Issue by sigalsax** [cyberark/secrets-provider-for-k8s#186]
The Secrets Provider process will retry on failure. There is a bug in the authn-client where on the first run, no matter what, the following failure log appears every time at the start of Secrets Provider.
```
ERROR: 2020/08/13 11:21:42 authenticator.go:140: CAKC011E Client certificate not found at '/etc/conjur/ssl/client.pem'
ERROR: 2020/08/13 11:21:42 authenticator.go:184: CAKC015E Login failed
ERROR: 2020/08/13 11:21:42 main.go:85: CSPFK010E Failed to authenticate
```

We need to address this by wrapping the authentication step in its own backoff loop

Bug documented [here](https://github.com/cyberark/conjur-authn-k8s-client/issues/119)

**Comment by orenbm** [comment]
@sigalsax can you link to the bug?

**Comment by abrahamko** [comment]
We are not going to implement this workaround, since current retry solution (every 30 seconds by default) is good enough.
We will wait for proper solution which wouldn't be here. Either in auth-kubernetes-client or in conjur server.
