### ISSUE TITLE
Version in the logs should not include git commit hash

### ISSUE THREAD

**Issue by orenbm** [cyberark/secrets-provider-for-k8s#258]
## Summary
Currently, when we print the project's version, we print also the commit hash:
```
INFO: 2020/11/10 15:32:04 main.go:20: CyberArk Secrets Provider for Kubernetes v1.1.0-e58708b starting up...
```

Fixed versions should not include the git commit tag and should include only the version.

Note: Once we fix this, we should also fix [this issue](https://github.com/cyberark/secrets-provider-for-k8s/issues/256) in the secrets-provider as it has a similar mechanism.

## Steps to Reproduce
1. run `docker pull cyberark/secrets-provider-for-k8s:1.1.0`
2. run `docker run cyberark/secrets-provider-for-k8s:1.1.0`

## Expected Results
The log shows the message `CyberArk Secrets Provider for Kubernetes v1.1.0 starting up...`

## Actual Results (including error logs, if applicable)
The log shows the message `CyberArk Secrets Provider for Kubernetes v1.1.0-e58708b starting up...`

## Reproducible
   * [x] Always 
   
## Version/Tag number
1.1.0

**Comment by sigalsax** [comment]
I am experiencing something different. We don't get the commit hash (I believe that is only in the authn-client), we get dev no matter what. See image below:
![Screen Shot 2020-11-12 at 7 54 28 AM](https://user-images.githubusercontent.com/19418506/98901426-72003580-24bc-11eb-893d-ba09ca3ce945.png)

**Comment by orenbm** [comment]
> I am experiencing something different. We don't get the commit hash (I believe that is only in the authn-client), we get dev no matter what. See image below:
> ![Screen Shot 2020-11-12 at 7 54 28 AM](https://user-images.githubusercontent.com/19418506/98901426-72003580-24bc-11eb-893d-ba09ca3ce945.png)
> 
> Or is this anticipatory for the change from [here](https://github.com/cyberark/secrets-provider-for-k8s/pull/257/files)?

yes, this issue assumed that we merged the other PR.

**Comment by eladkug** [comment]
Duplicate to https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-9877
