### ISSUE TITLE
Release the secrets provider version that includes the authn-k8s client v0.19.0

### ISSUE THREAD

**Issue by izgeri** [cyberark/secrets-provider-for-k8s#267]
To include v0.19.0 in the next OSS suite release, we'd like to bump the downstream project versions so that they include the same version of the authn-k8s client library.

AC:
- [ ] There is a new Secrets Provider release that includes the authn-k8s client version bump to v0.19.0

**Comment by izgeri** [comment]
@cyberark/palmtree how many manual steps are required in a release? If I submit a version bump PR, is it much more complicated than adding a tag and copying the helm tgz into the helm-charts repo? If it's pretty simple, I'm happy to help with getting this release out.

**Comment by sigalsax** [comment]
@izgeri See [here](https://github.com/cyberark/secrets-provider-for-k8s/blob/master/CONTRIBUTING.md#releases) for more details but in addition to that we need to push to Redhat + if docs need to be written we should make sure that they are

We package the helm charts as part of our pipeline so you don't have to 😄 . See [here](https://github.com/cyberark/secrets-provider-for-k8s/blob/master/CONTRIBUTING.md#push-helm-package)

Other than that, we should be golden ✨

**Comment by izgeri** [comment]
@sigalsax it looks to me like there is nothing on master that requires doc updates: https://github.com/cyberark/secrets-provider-for-k8s/compare/v1.1.0...master

who should I check with to verify this? @InbalZilberman @alexkalish ?
