### ISSUE TITLE
Helm namespace is ignored

### ISSUE THREAD

**Issue by liavyona** [cyberark/secrets-provider-for-k8s#290]
## Summary
The secrets provider’s helm chart uses `{{ .Release.namespace }}`  and it won’t work! It’s supposed to be 
`{{ .Release.Namespace}}`
## Steps to Reproduce
`helm template secrets-provider  -f=values.yaml  --namespace=main | grep namespace`

## Expected Results
I would like to set my own namespace for the secrets provider chart

## Actual Results (including error logs, if applicable)
namepace was null
## Reproducible
   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number
Always
Can you describe the environment in which this product is running? Is it running on a VM / in a container / in a cloud? 
EKS
## Additional Information
https://stackoverflow.com/questions/51760772/why-is-release-namespace-rendered-empty

**Comment by izgeri** [comment]
Note:

I was able to verify that the current results give (run from the root of this project, with the cyberark helm repo installed):
```
$ helm template cyberark/secrets-provider --namespace=main -f helm/secrets-provider/values.yaml | grep namespace
  namespace:
  namespace: 
  namespace: 
  namespace: 
    namespace: 
  namespace: 
              fieldPath: metadata.namespace
```

With the fix in #291, it now gives
```
$ helm template helm/secrets-provider/ --namespace=main -f helm/secrets-provider/values.yaml | grep namespace
  namespace: main
  namespace: main
  namespace: main
  namespace: main
    namespace: main
  namespace: main
              fieldPath: metadata.namespace
```
