### ISSUE TITLE
Secrets Provider leverages common Conjur configuration

### ISSUE THREAD

**Issue by alexkalish** [cyberark/secrets-provider-for-k8s#299]
## User Story

**As an** app/workload SRE
**I want** the Secrets Provider sidecar/init container to leverage common cluster and namespace Conjur configuration    
**So that** I need only be concerned with configuration specific to my workload. 

### Additional Details

None

## Implementation/Solution Notes

**Comment by izgeri** [comment]
There are no specific implementation tasks tied to this story, so closing it for now.
