### ISSUE TITLE
US-02: Static configuration as self-contained YAML

### ISSUE THREAD

**Issue by alexkalish** [cyberark/secrets-provider-for-k8s#332]
## User Story

**As a** application developer 
**I want** all static Secrets Provider configuration to be provided as self-contained YAML snippets 
**So that** I can simply copy/paste boilerplate content. 

### Test Scenarios

*If desired, add one or more test scenarios required for user story acceptance.
Ideally, they are executed by automated tests. For more details on Gerkin syntax,
see this [article](https://cucumber.io/docs/gherkin/reference/)*

**Given** <this setup/context>
**When** <an action/event occurs>
**Then** <the expected behavior/outcome>

### Implementation Tasks

*The following issues have been created to implement this user story:*

* <issue link>

**Comment by diverdane** [comment]
@alexkalish,

Just to be sure... If we make the snippets completely static (can be directly copy/pasted), then we would be including a fixed Secrets Provider image/tag. This would probably point to Secrets Provider `latest` image, which means latest released version.

A couple of comments/questions:
- Using `latest` released version is probably appropriate for most deployments. There may be some corner cases where
   customers might want to pin to a fixed version so there are no surprises e.g. when we make a
   major (breaking) release. So maybe we provide the fixed snippet and document that the SP image:tag
   can be modified as needed?
- For the corresponding Helm partial named template, I think we would want to have the image:tag
   templatized with a default value to allow for corner cases.

Does this match your expectations?

**Comment by alexkalish** [comment]
@diverdane: I had not thought about the image tag.  We probably shouldn't encourage using `latest`.  Unless you know of any others, I'm fine with the version tag being the only exception to the user story here.
