### ISSUE TITLE
There is a defined project structure for M1 push to file

### ISSUE THREAD

**Issue by rpothier** [cyberark/secrets-provider-for-k8s#342]
As a M1 developer,
I want a defines project structure,
So that development can be coordinated between developers.

For the M1 push to file, the general project layout should be defined.

- There should be a directory(s) where the components should be places.
   Verify if placing in pkg is the best location.
- Subdirectories for each component should be defined?

## Acceptance Criteria

- [ ] Subdirectories are created and the project layout is defined.

**Comment by jtuttle** [comment]
Need someone to propose something as a strawman argument.
