### ISSUE TITLE
K8s Dev UX: Search and Replace (M1.1)

### ISSUE THREAD

**Issue by Conjur-oss** [cyberark/secrets-provider-for-k8s#351]
h2. Overall Outcome

Customer serves secrets through volume mounted files to an existing application workload deployed into K8s.  This only requires modifying the application deployment manifest and not the application itself.  This essentially matches Novartis’ primary desired use-case.

h2. Epic/Release Outcome

Exact functionality TBD.  However, at a high-level, allow users to bring pre-existing configuration file/content, replace placeholders with secrets from Conjur and then write the resulting updating file/content to a volume shared with the application.

h2. References
* PRD: [Conjur Developer Experience|https://cyberark365.sharepoint.com/:w:/r/sites/Conjur/_layouts/15/Doc.aspx?sourcedoc=%7B956DB935-7E3D-4D88-B964-188BCB6F7729%7D&file=Conjur%20Developer%20Experience%20for%20K8s%20PRD.docx&action=default&mobileredirect=true]
* Feature Doc: TODO
* Solution Design: TODO

**Comment by Conjur-oss** [comment]
https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-11465

**Comment by szh** [comment]
@Conjur-oss why did you reopen this? This has been completed for months.
