### ISSUE TITLE
P2F bash mode does not work for secret names with dashes

### ISSUE THREAD

**Issue by Conjur-oss** [cyberark/secrets-provider-for-k8s#405]
##Bug description
See attached image for details.

##Found in version
12.4

##Workaround Complexity
NA

##Workaround Description

##Affects Version/s

##Link to JIRA bug
https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-14674

**Comment by Conjur-oss** [comment]
https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-14674

**Comment by john-odonnell** [comment]
[Dashes are invalid characters in Bash names](https://unix.stackexchange.com/a/23660), so this behavior is expected.
The error message for this failure was clarified, and this issue is closed by #416.
