### ISSUE TITLE
Secrets Provider Conjur Secrets Rotation Support

### ISSUE THREAD

**Issue by Conjur-oss** [cyberark/secrets-provider-for-k8s#419]

**Comment by Conjur-oss** [comment]
https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-15242

**Comment by bademux** [comment]
Could one please elaborate on how it is related to https://github.com/cyberark/secrets-provider-for-k8s/blob/main/ROTATION.md

**Comment by szh** [comment]
Closing as completed.
