### ISSUE TITLE
Image name was changed

### ISSUE THREAD

**Issue by Tovli** [cyberark/secrets-provider-for-k8s#45]
The image name was changed from 
cyberark/cyberark-secrets-provider-for-k8s to cyberark/secrets-provider-for-k8s

Need to check with Inbal and change the image name if a revert is needed or change the Docs if the image name is ok

**Comment by sigalsax** [comment]
The image name is actually `cyberark/secrets-provider-for-k8s` and this should just be updated in the docs. I opened a bug for docs TW to address: https://github.com/cyberark/conjur-docs/issues/606
