### ISSUE TITLE
Add automation testing for Openshift 3.9

### ISSUE THREAD

**Issue by sigalsax** [cyberark/secrets-provider-for-k8s#49]
A previous PR has been opened that covers automation for GKE, Openshift 3.11 and 3.10 (https://github.com/cyberark/secrets-provider-for-k8s/pull/46) for the Secrets Provider for K8s. This is a separate card to support 3.9. At current, tests run manually and this effort is to build automaticity into our pipeline for 3.9

Open questions to consider:

Do we want to support 3.9? Are our customers on 3.9 still? This is a decision that needs to be had between the team and PM
Why do we get a different response from 3.11/3.10 and 3.9. Maybe there is something in our scripts that is not supported in 3.9 - deleting deployments, pods, etc. See authn-client and demo

**Comment by Tovli** [comment]
Closing as we won't add automation for ocp 3.9 at this stage
