### ISSUE TITLE
Standardised CHANGELOG exists, and is validated via pipeline

### ISSUE THREAD

**Issue by izgeri** [cyberark/secrets-provider-for-k8s#65]
If the repo has a changelog that doesn't meet the standard, do try to change earlier entries to match the standard.
If the repo doesn't have a changelog use this as a starter:
```
# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/)
and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.html).

## [Unreleased]
```

## Acceptance criteria
- [ ] CHANGELOG.md exists and follows the KeepAChangeLog format. For reference consult https://github.com/cyberark/conjur/blob/master/CHANGELOG.md.
- [ ] Add parse-changelog validation step to Jenkinsfile. For reference consult  https://github.com/cyberark/conjur/blob/master/Jenkinsfile#L27.

**Comment by izgeri** [comment]
@JakeQuilty when you get to this repo please make sure to tag @Tovli as a reviewer on your PR

**Comment by JakeQuilty** [comment]
PR Link:https://github.com/cyberark/secrets-provider-for-k8s/pull/67
