### ISSUE TITLE
Secrets provider publishes a Red Hat certified image to the RH container registry

### ISSUE THREAD

**Issue by izgeri** [cyberark/secrets-provider-for-k8s#75]
[Secretless](https://access.redhat.com/containers/#/registry.connect.redhat.com/cyberark/secretless-broker) and the [authn-k8s client](https://access.redhat.com/containers/#/registry.connect.redhat.com/cyberark/conjur-authn-k8s-client) are both already publishing to Red Hat.

This is connected to the Aha card: https://cyberark.aha.io/features/AAM-298

AC:
- [x] Work with infrastructure to create a new project in our Red Hat account for the secrets provider image (this includes getting the project-specific API key)
- [ ] Update the project pipeline to authenticate to the RH container registry using the project-specific API key and push the updated image on publish to RH as well as dockerhub

Developer notes:
- There are (private) guidelines [here](https://github.com/conjurinc/docs/blob/master/reference/infrastructure/openshift_registry_upload_guide.md) for adding a project to the RH registry that you may find useful
- To see how Secretless added this support, you can see [PR 1141](https://github.com/cyberark/secretless-broker/pull/1141) and [PR 1149](https://github.com/cyberark/secretless-broker/pull/1149/files) - unfortunately, it was done in two steps since the per-project API key wasn't clear until publish time.

**Comment by sigalsax** [comment]
@izgeri, in terms of the distribution method for the REHL image, do we only want it to be available via marketplace or both marketplace + registry? I was thinking both, correct?

<img width="624" alt="Screen Shot 2020-05-21 at 10 54 52 AM" src="https://user-images.githubusercontent.com/19418506/82747680-3e154480-9da4-11ea-890e-8e6b4ca88d50.png">

**Comment by izgeri** [comment]
@sigalsax I would look at how other images that are already published are configured, and copy that configuration as much as possible. I'm not sure the exact answer to this question, except that we definitely want it on RH registry, so that implies the first option.
