### ISSUE TITLE
Secrets Provider for K8s - support rotations and several apps

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/secrets-provider-for-k8s#98]
### Overview
We would like to improve Secret Provider for K8s so that:

- Secrets Provider support rotations 
 - Secrets Provider runs and deployed without affecting the app deployment or app life cycle
 - Secrets Provider can serve many apps

**Comment by eladkug** [comment]
There is another detailed [Epic](https://app.zenhub.com/workspaces/palmtree-5d99d900491c060001c85cba/issues/cyberark/secrets-provider-for-k8s/102)
